title: Little Hearts Learning Centre
description: Creating enabling spaces to realize the educational and functional needs of children
url: ""
baseurl: ""

markdown: kramdown
permalink: pretty

collections:
  programs:
    output: false
  activities:
    output: true
    permalink: /activities/:name/
  testimonials:
    output: true
    permalink: /testimonials/:name/

defaults:
  - scope:
      path: ""
    values:
      layout: page
